stages:          # Các giai đoạn của pipeline
  - build
  - test
  - deploy

build-job:       # Job 1: Build ứng dụng
  stage: build
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: clone
  tags:
    - local     # (tag này phải trùng với tag bạn đặt khi tạo runner)
  script:
    - echo "Building Spring Boot app..."
    - mvn clean package -DskipTests

test-job:        # Job 2: Test ứng dụng
  stage: test
  tags:
    - local
  script:
    - echo "Running unit tests..."
    - mvn test

deploy-job:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - local
  script:
    - echo "Deploy successfull!"

