openapi:
  services:
    api-docs: api-services
    server: http://localhost:8080
    title: API services
    version: v1.0.0
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kemshop
    username: root
    password: 250104
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
---
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
---
